use anchor_lang::prelude::*;

#[error_code]
pub enum VsrError {
    #[msg("")]
    InvalidGoverningMint,
    #[msg("")]
    GoverningTokenNonZero,
    #[msg("")]
    OutOfBoundsDepositEntryIndex,
    #[msg("")]
    InsufficientUnlockedTokens,
    #[msg("")]
    InvalidLockupPeriod,
    #[msg("")]
    DebugInstruction,
    #[msg("")]
    InvalidAuthority,
    #[msg("")]
    InvalidTokenOwnerRecord,
    #[msg("")]
    InvalidRealmAuthority,
    #[msg("")]
    VoterWeightOverflow,
    #[msg("")]
    LockupSaturationMustBePositive,
    #[msg("")]
    InternalProgramError,
    #[msg("")]
    InsufficientLockedTokens,
    #[msg("")]
    InternalErrorBadLockupVoteWeight,
    #[msg("")]
    DepositStartTooFarInFuture,
    #[msg("")]
    VaultTokenNonZero,
    #[msg("")]
    NodeDepositReservedEntryIndex,
    #[msg("")]
    InactiveDepositEntry,
    #[msg("")]
    NotOrdinaryDepositEntry,
    #[msg("")]
    CanNotShortenLockupDuration,
    #[msg("")]
    NodeDepositUnreleasableAtPresent,
    #[msg("")]
    ZeroDepositAmount,
    #[msg("")]
    NodeSecurityDepositMustBePositive,
    #[msg("")]
    DuplicateNodeDeposit,
    #[msg("")]
    ActiveDepositEntryIndex,
    #[msg("")]
    InvalidLockupDuration,
}
