[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voter_stake_registry = "Bvsr2wYoKA1btgu3DGUFZ4KKtdwWMAQA5vvd4FKRPi8T"
circuit-breaker = "CirC9HGGQgTk8XA8ARBgXkaBDDt3Jejs3F8ezTNKp8Q"

[workspace]
members = [
  "programs/voter-stake-registry",
  "programs/circuit-breaker",
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

# spl-governance
[[test.genesis]]
address = "GovernanceProgramTest1111111111111111111111"
program = "./tests-genesis/governance.so"